import React from 'react';
import PropTypes from 'prop-types';
import { Card, Button } from './index.js';

/**
 * ReportCard Component
 * Displays report information in a card format
 * 
 * @param {Object} props - Component props
 * @param {Object} props.report - Report data
 * @param {boolean} props.showActions - Whether to show action buttons
 * @param {Function} props.onEdit - Edit handler
 * @param {Function} props.onDelete - Delete handler
 * @param {Function} props.onView - View handler
 */
function ReportCard({ report, showActions = true, onEdit, onDelete, onView }) {
  if (!report) {
    return null;
  }

  // Format date
  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString();
  };

  // Format time
  const formatTime = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleTimeString();
  };

  // Get report type display name
  const getReportTypeDisplay = (type) => {
    const typeMap = {
      'daily_summary': 'Daily Summary',
      'monthly_summary': 'Monthly Summary',
      'yearly_summary': 'Yearly Summary',
      'income_expense': 'Income vs Expense',
      'category_summary': 'Category Summary',
      'student_balances': 'Student Balances',
      'custom': 'Custom Report'
    };
    return typeMap[type] || type || 'Unknown';
  };

  // Format file size if available
  const formatFileSize = (filePath) => {
    if (!filePath) return null;
    // Extract file name from path
    const parts = filePath.split('/');
    return parts[parts.length - 1];
  };

  // Calculate data size
  const calculateDataSize = (data) => {
    if (!data) return '0 KB';
    const size = JSON.stringify(data).length;
    if (size < 1024) return `${size} B`;
    if (size < 1024 * 1024) return `${(size / 1024).toFixed(2)} KB`;
    return `${(size / (1024 * 1024)).toFixed(2)} MB`;
  };

  return (
    <Card
      title={report.title || 'Untitled Report'}
      subtitle={`${getReportTypeDisplay(report.report_type)} - ${formatDate(report.created_at)}`}
      className="report-card"
    >
      <div className="report-info">
        <div className="report-detail">
          {report.description && (
            <div className="detail-row">
              <span className="detail-label">Description:</span>
              <span className="detail-value">{report.description}</span>
            </div>
          )}

          <div className="detail-row">
            <span className="detail-label">Report Type:</span>
            <span className="detail-value badge badge-info">
              {getReportTypeDisplay(report.report_type)}
            </span>
          </div>

          {report.generated_by_name && (
            <div className="detail-row">
              <span className="detail-label">Generated By:</span>
              <span className="detail-value">{report.generated_by_name}</span>
            </div>
          )}

          {report.file_path && (
            <div className="detail-row">
              <span className="detail-label">File:</span>
              <span className="detail-value">{formatFileSize(report.file_path)}</span>
            </div>
          )}

          {report.report_data && (
            <div className="detail-row">
              <span className="detail-label">Data Size:</span>
              <span className="detail-value">{calculateDataSize(report.report_data)}</span>
            </div>
          )}

          <div className="detail-row">
            <span className="detail-label">Created:</span>
            <span className="detail-value">{formatDate(report.created_at)} {formatTime(report.created_at)}</span>
          </div>
        </div>

        {report.parameters && (
          <div className="report-parameters">
            <div className="parameter-row">
              <strong>Parameters:</strong>
              <pre className="parameter-value">{JSON.stringify(report.parameters, null, 2)}</pre>
            </div>
          </div>
        )}
      </div>

      {showActions && (
        <div className="report-actions">
          {onView && (
            <Button variant="outline" size="sm" onClick={() => onView(report)}>
              View
            </Button>
          )}
          {onEdit && (
            <Button variant="secondary" size="sm" onClick={() => onEdit(report)}>
              Edit
            </Button>
          )}
          {onDelete && (
            <Button variant="danger" size="sm" onClick={() => onDelete(report)}>
              Delete
            </Button>
          )}
        </div>
      )}
    </Card>
  );
}

ReportCard.propTypes = {
  report: PropTypes.object.isRequired,
  showActions: PropTypes.bool,
  onEdit: PropTypes.func,
  onDelete: PropTypes.func,
  onView: PropTypes.func
};

export default ReportCard;
